[package]
name = "ankyra-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Proc-macros for the ankyra Klipper MCU protocol framework."

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits", "visit"] }
quote = "1"
proc-macro2 = "1"
proc-macro-error2 = "2"
ankyra-assemble = { path = "../ankyra-assemble", version = "0.1.0" }

[dev-dependencies]
trybuild = "1"
ankyra = { path = "../ankyra" }
serde_json = "1"
rustversion = "1"
